version: 2.1

orbs:
  node: circleci/node@4.2.0
  cypress: cypress-io/cypress@1

jobs:
  test:
    docker:
      - image: circleci/node:15-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
      - run: yarn lint
      - run:
          command: yarn test:ci
          name: "Testing Jest"
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
      - run: yarn cypress install && yarn ci:cypress-run
      - run: yarn build
  deploy:
    docker:
      - image: circleci/node:15-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Configure GIT
          command: |
            git config user.email "ci-build@pjog.de"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "85:04:0a:cd:ae:a4:30:4a:c1:86:67:fb:d7:91:8e:98"
      - run: yarn deploy
workflows:
  test_my_app:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master


