version: 2.1

orbs:
  node: circleci/node@4.2.0
  cypress: cypress-io/cypress@1

jobs:
  test:
    docker:
      - image: circleci/node:15-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
      - run: yarn lint
      - run: yarn test
      - cypress/install:
          build: "yarn build"
          requires:
            - node/install-packages
      - cypress/run:
          requires:
            - cypress/install
          record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'npm start' # start server before running tests
          wait-on: "http://localhost:3000/Reactify-Search"

      - run: yarn build
workflows:
  test_my_app:
    jobs:
      - test