version: 2.1

orbs:
  node: circleci/node@4.2.0
  cypress: cypress-io/cypress@1

jobs:
  test:
    docker:
      - image: circleci/node:15-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
      - run: yarn lint
      - run: yarn test
      - run: yarn cypress install && yarn ci:cypress-run
      - run: yarn build
  deploy:
    docker:
      - image: circleci/node:15-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn deploy
workflows:
  test_my_app:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master


